format_version: 10
pipelines:
  benchmark-comparison:
    group: defaultGroup
    label_template: "benchmark-${COUNT}"
    lock_behavior: unlockWhenFinished

    parameters:
      CONFIGURATIONS: "all"
      RUN_COUNT: "3"

    materials:
      git:
        git: https://github.com/ddcn4-1/frontend-v3.git
        branch: feat/CLD-32
        destination: repo

    environment_variables:
      AWS_REGION: "ap-northeast-2"
      NODE_VERSION: "22"
      PNPM_VERSION: "9.15.0"

    stages:
      - baseline:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "baseline"
            PNPM_CACHE: "false"
            TURBO_CACHE: "false"
            S3_REMOTE: "false"
            S3_REGION: ""
            PARALLEL_BUILD: "false"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - baseline
                      - "false"
                      - "false"
                      - "false"
                      - ""
                      - "false"
                    working_directory: ""

      - with-pnpm-cache:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "with-pnpm-cache"
            PNPM_CACHE: "true"
            TURBO_CACHE: "false"
            S3_REMOTE: "false"
            S3_REGION: ""
            PARALLEL_BUILD: "false"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - with-pnpm-cache
                      - "true"
                      - "false"
                      - "false"
                      - ""
                      - "false"
                    working_directory: ""

      - with-turbo-cache:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "with-turbo-cache"
            PNPM_CACHE: "true"
            TURBO_CACHE: "true"
            S3_REMOTE: "false"
            S3_REGION: ""
            PARALLEL_BUILD: "false"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - with-turbo-cache
                      - "true"
                      - "true"
                      - "false"
                      - ""
                      - "false"
                    working_directory: ""

      - with-s3-apne2:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "with-s3-apne2"
            PNPM_CACHE: "true"
            TURBO_CACHE: "false"
            S3_REMOTE: "true"
            S3_REGION: "ap-northeast-2"
            PARALLEL_BUILD: "false"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
                - aws-cli
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - with-s3-apne2
                      - "true"
                      - "false"
                      - "true"
                      - ap-northeast-2
                      - "false"
                    working_directory: ""

      - with-s3-usea1:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "with-s3-usea1"
            PNPM_CACHE: "true"
            TURBO_CACHE: "false"
            S3_REMOTE: "true"
            S3_REGION: "us-east-1"
            PARALLEL_BUILD: "false"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
                - aws-cli
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - with-s3-usea1
                      - "true"
                      - "false"
                      - "true"
                      - us-east-1
                      - "false"
                    working_directory: ""

      - parallel-builds:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "parallel-builds"
            PNPM_CACHE: "true"
            TURBO_CACHE: "false"
            S3_REMOTE: "false"
            S3_REGION: ""
            PARALLEL_BUILD: "true"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - parallel-builds
                      - "true"
                      - "false"
                      - "false"
                      - ""
                      - "true"
                    working_directory: ""

      - all-optimizations:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "all-optimizations"
            PNPM_CACHE: "true"
            TURBO_CACHE: "true"
            S3_REMOTE: "false"
            S3_REGION: ""
            PARALLEL_BUILD: "true"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - all-optimizations
                      - "true"
                      - "true"
                      - "false"
                      - ""
                      - "true"
                    working_directory: ""

      - all-with-s3-apne2:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: false
          approval:
            type: success

          environment_variables:
            CONFIG_NAME: "all-with-s3-apne2"
            PNPM_CACHE: "true"
            TURBO_CACHE: "false"
            S3_REMOTE: "true"
            S3_REGION: "ap-northeast-2"
            PARALLEL_BUILD: "true"

          jobs:
            benchmark:
              timeout: 30
              resources:
                - nodejs
                - pnpm
                - aws-cli
              artifacts:
                - build:
                    source: repo/benchmark-results
                    destination: results
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/benchmark.sh
                      - all-with-s3-apne2
                      - "true"
                      - "false"
                      - "true"
                      - ap-northeast-2
                      - "true"
                    working_directory: ""

      - compare-results:
          fetch_materials: true
          keep_artifacts: true
          clean_workspace: true
          approval:
            type: success

          jobs:
            analyze:
              timeout: 10
              resources:
                - nodejs
              artifacts:
                - build:
                    source: comparison-report
                    destination: report
              tasks:
                - fetch:
                    pipeline: benchmark-comparison
                    stage: baseline
                    job: benchmark
                    source: results
                    destination: all-results/baseline

                - fetch:
                    pipeline: benchmark-comparison
                    stage: with-pnpm-cache
                    job: benchmark
                    source: results
                    destination: all-results/with-pnpm-cache

                - fetch:
                    pipeline: benchmark-comparison
                    stage: with-turbo-cache
                    job: benchmark
                    source: results
                    destination: all-results/with-turbo-cache

                - fetch:
                    pipeline: benchmark-comparison
                    stage: with-s3-apne2
                    job: benchmark
                    source: results
                    destination: all-results/with-s3-apne2

                - fetch:
                    pipeline: benchmark-comparison
                    stage: with-s3-usea1
                    job: benchmark
                    source: results
                    destination: all-results/with-s3-usea1

                - fetch:
                    pipeline: benchmark-comparison
                    stage: parallel-builds
                    job: benchmark
                    source: results
                    destination: all-results/parallel-builds

                - fetch:
                    pipeline: benchmark-comparison
                    stage: all-optimizations
                    job: benchmark
                    source: results
                    destination: all-results/all-optimizations

                - fetch:
                    pipeline: benchmark-comparison
                    stage: all-with-s3-apne2
                    job: benchmark
                    source: results
                    destination: all-results/all-with-s3-apne2

                - exec:
                    command: /bin/bash
                    arguments:
                      - repo/gocd/scripts/compare-results.sh
                    working_directory: ""
