name: Epic
description: Track company-wide initiatives or multi-sprint work
labels:
  - Epic
projects:
  - ddcn4-1/10
body:
  - type: textarea
    id: objective
    attributes:
      label: 목표 기능 내용
      description: Epic의 목표와 달성하고자 하는 기능을 설명해주세요.
      placeholder: "예) 사용자가 소셜 로그인을 통해 간편하게 회원가입 및 로그인할 수 있도록 합니다."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 작업 상세 내용
      description: Epic을 구성하는 세부 작업들을 나열해주세요.
      placeholder: |
        - [ ] Task 1: 구글 OAuth 연동
        - [ ] Task 2: 카카오 OAuth 연동
        - [ ] Task 3: 소셜 로그인 UI 구현
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: 관련 문서, 이슈, 또는 참고 자료의 링크를 추가해주세요.
      placeholder: |
        - 관련 이슈: #123
        - 참고 문서: https://...
    validations:
      required: false
