name: Task - Bug
description: Report a defect that still maps to a Jira Task
title: "BUG: "
labels:
  - Task
  - bug
projects:
  - ddcn4-1/10
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 발생한 버그에 대해 설명해주세요.
      placeholder: "예) 로그인 버튼 클릭 시 페이지가 응답하지 않습니다."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      description: 버그를 재현할 수 있는 단계를 설명해주세요.
      placeholder: |
        1. 로그인 페이지로 이동
        2. 이메일과 비밀번호 입력
        3. 로그인 버튼 클릭
        4. 에러 발생
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 정상적으로 동작해야 하는 방식을 설명해주세요.
      placeholder: "로그인 성공 후 대시보드 페이지로 이동해야 합니다."
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로 발생하는 동작을 설명해주세요.
      placeholder: "페이지가 멈추고 콘솔에 에러가 출력됩니다."
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: 스크린샷, 로그, 또는 관련 자료를 추가해주세요.
      placeholder: |
        - 에러 로그: ```error message```
        - 스크린샷: [이미지 첨부]
    validations:
      required: false
